### ISSUE TITLE
Add a splashscreen

### ISSUE THREAD

**Issue by ksiazkowicz** [ksiazkowicz/lightbulb#10]
This app really needs a splashscreen.

**Comment by huellif** [comment]
I will try to later today ;)

**Comment by ksiazkowicz** [comment]
Thanks. Could you have a look at the sounds issue? It would be better if it used some native stuff for that if possible.

**Comment by huellif** [comment]
should be possible ;)

**Comment by huellif** [comment]
I can't compile you latest version, it's broken (MessageListModel is missing)

**Comment by ksiazkowicz** [comment]
I forgot to commit one file. Done.

**Comment by ksiazkowicz** [comment]
Well, this is interesting:
[Qt Message] QEglContext::createSurface(): Unable to create EGL surface, error = 0x3003
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 640x640 pixmap
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 640x640 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 512x512 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 256x256 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 128x128 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 64x64 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 32x32 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 16x16 image
[Qt Message] drawImageTiled: Failed to create 8x8 tile, giving up
[Qt Message] QEglContext::createSurface(): Unable to create EGL surface, error = 0x3003
[Qt Message] QEglContext::createSurface(): Unable to create EGL surface, error = 0x3003
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 640x640 pixmap
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 640x640 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 512x512 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 256x256 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 128x128 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 64x64 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 32x32 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 16x16 image
[Qt Message] drawImageTiled: Failed to create 8x8 tile, giving up
[Qt Message] QVGPaintEngine::drawTextItem: OpenVG fonts are not supported by the OpenVG engine
[Qt Message] QEglContext::createSurface(): Unable to create EGL surface, error = 0x3003
[Qt Message] QSymbianControl::doDraw: EGL surface creation has failed, abort 
[Qt Message] QEglContext::createSurface(): Unable to create EGL surface, error = 0x3003
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 640x640 pixmap
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 640x640 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 512x512 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 256x256 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 128x128 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 64x64 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 32x32 image
[Qt Message] QVGImagePool: cannot reclaim sufficient space for a 16x16 image
[Qt Message] drawImageTiled: Failed to create 8x8 tile, giving up
[Qt Message] QVGPaintEngine::drawTextItem: OpenVG fonts are not supported by the OpenVG engine
[Qt Message] QEglContext::createSurface(): Unable to create EGL surface, error = 0x3003

**Comment by ksiazkowicz** [comment]
I taken care of something else and guess what? It suddenly started working. o.o

Closing.
