### ISSUE TITLE
Webkit in messages view

### ISSUE THREAD

**Issue by ksiazkowicz** [ksiazkowicz/lightbulb#16]
I noticed QML performace in rendering message view is bad. The general idea is to use QtWebKit for this purpose and using JavaScript's document.write() to add new messages.

This thing can, first - improve performance. Second - make message view completely theme-able. It would also be awesome if Lightbulb used the same files which are already used by Messaging app.

To be noted - most IMs I've used adapted some web rendering engines for this purpose as well - Adium, WTW, AQQ, Pidgin. So lets at least give it a shot.

**Comment by huellif** [comment]
that's a great idea :)
Finally smilies would be possible

**Comment by ksiazkowicz** [comment]
I'm unable to find a way to append stuff to WebView. Also, it makes app work slower actually.

Too bad. Btw. smilies are possible, I just broke the code while porting it to js, doesn't matter.
