### ISSUE TITLE
Message sometimes doesn't appear

### ISSUE THREAD

**Issue by ksiazkowicz** [ksiazkowicz/lightbulb#20]
Something probably related to SQL code. Messages themselves are being stored properly, so it's an issue with refreshing.

**Comment by ghost** [comment]
its correct... My message was sent but it's not appear in conversation

**Comment by ksiazkowicz** [comment]
Issue is definitely connected to database code. I managed to test it out properly today and it can't handle messages with quote marks or other special signs (',",% etc.). I need to add some code to avoid this, for example, changing the message text before inserting it to database to work this thing around.
