### ISSUE TITLE
"Reconnection Feature" is not working 

### ISSUE THREAD

**Issue by maxicaleca** [ksiazkowicz/lightbulb#30]
Imagine you are connected to facebook chat (online)....
I realized that when the internet connection is down and then returns back , the application appears in offline mode and it will keep saying that until the user select online status.

 You could possibly add a reload feature that makes the app request internet connection every 2 minutes for example, and if the apps found one, then it should restore the last status. 

I always use as a reference the Whatsapp app. 

This is an important issue cause you could lose some messages.

Regards,

**Comment by ksiazkowicz** [comment]
This is weird, but well, this feature never worked properly apparently.

**Comment by ksiazkowicz** [comment]
Depends on #48
