### ISSUE TITLE
"Long tap closes the chat" Important Suggestion

### ISSUE THREAD

**Issue by maxicaleca** [ksiazkowicz/lightbulb#31]
Sorry for posting so many issues, but I swear they are worth it. Since "0.3 Milestone 3 Pre-Release" version you implemented new features such as:

1)"long tap closes the app, single one just hides it"
2)long tap closes the chat, single one just goes back to contact list"

Number one it´s excellent, no problems. The thing is on number two

Don´t you think it would be convenient to add an algoritm that closes the chat if the user still tapping during "x" seconds? So the user save up time closing them

........Take my issues as a help, not as an attack....... haha

**Comment by ksiazkowicz** [comment]
I'd rather add an option to close them from chats dialog, I just keep forgetting about it.
