### ISSUE TITLE
Freezing screen after returning back to contacts

### ISSUE THREAD

**Issue by maxicaleca** [ksiazkowicz/lightbulb#33]
I dont know why, but if am chatting with someone and then pressed the "go back" button to go to contacts it freezes at least 5 or 6 seconds, I am pretty sure that is not due to the refresh of online contacts.

Do you know why? thank you very much

**Comment by maxicaleca** [comment]
Forgot to mention that I have already tested on the latest version and it has the same issue :(

**Comment by ksiazkowicz** [comment]
Works for me. How many contacts do you have? Do you have avatars enabled?

**Comment by maxicaleca** [comment]
Avatars are already enabled and I have between 60 to 70 contacts. Its a bit weird. 90 percent of the times this happens, I dont know exactly why. So you dont have this problem?

**Comment by ksiazkowicz** [comment]
I noticed having lots of messages in a chat could cause a delay when going into chat, switching between chats and going back.

I added a feature to limit visible messages, if you use it, it should reduce the amount of time needed to load messages view and unload it from memory. I hope this can solve your issue.

**Comment by maxicaleca** [comment]
I tested and happened exactly what you said, in contacts without any conversation, there isnt delays switching or going back.

The feauture i guess it will appear at 0.3-alphaM3. Oh by the way, if you go to settings and return back it appears the "same" issue, then i realized why did you add a new section "preferences".

If I can help you with something. just ask me. (im not a programmer , but in ideas ofcourse :D). More over, if there is any other way to contact you more quickly, it would be cool !

regards!

**Comment by ksiazkowicz** [comment]
So I guess, the issue is resolved. If you want to help with testing and happen to have a hacked phone, I can give you a trunk build for testing. Thank you for your feedback.

The best way to report suggestions and ideas is using GitHub, cause this way I won't forget about it. But sure, there is a way. If you happen to use Jabber or simply Google Talk/Hangouts, you could try reaching me on maciej_j@jid.pl.
