### ISSUE TITLE
"Seen feature"

### ISSUE THREAD

**Issue by maxicaleca** [ksiazkowicz/lightbulb#36]
Is this possible in a future?

**Comment by ksiazkowicz** [comment]
Could you be more specific, please?

**Comment by maxicaleca** [comment]
Yes, sorry.  I meant if the "Seen xx:xx" option from facebook could be availble on lightbulb.

http://i.i.cbsi.com/cnwk.1d/i/tim/2012/08/21/Facebook_Chat_Seen.jpg

Thanks

**Comment by ksiazkowicz** [comment]
Impossible to do it over XMPP, sorry.
