### ISSUE TITLE
Which improvements are going to appear on the next version?

### ISSUE THREAD

**Issue by maxicaleca** [ksiazkowicz/lightbulb#38]
Pizarz, I wanted to know what the questions says if you dont mind :) and also
 When are you going to release it  ? just to know im ansious haha.

PD: I added you to Skype, you need to accept my request (maxilocoterr)

**Comment by ksiazkowicz** [comment]
This: https://github.com/ksiazkowicz/lightbulb/issues?milestone=2&state=open

And some minor bugfixes as well.
