### ISSUE TITLE
Some Emoticons are still not working 

### ISSUE THREAD

**Issue by bhavin192** [ksiazkowicz/lightbulb#44]
![bug1](https://cloud.githubusercontent.com/assets/5154532/2808704/4b9b4536-cd40-11e3-9b6c-7d90a9ce7223.jpg)

For peng it should be <(") not <('') 
in images on side is from fb

![bug2](https://cloud.githubusercontent.com/assets/5154532/2808705/658dc284-cd40-11e3-8bc2-84db142605ff.jpg)

don't know why these two doesn't work

**Comment by ksiazkowicz** [comment]
Emoticon parser apparently won't recognize them properly. I'll try debugging it by spitting out whatever parser receives to the console.

**Comment by ksiazkowicz** [comment]
Btw. you've forgot to commit kiki.png.

**Comment by bhavin192** [comment]
I have used -a in commit :(
I will push and send a pull request ;)

EDIT: Done
